// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmbeoyduvmacwkgcfijq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtYmVveWR1dm1hY3drZ2NmaWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDA3MzgsImV4cCI6MjA2ODkxNjczOH0.5gCIGdjs3QzjZCa1zRiTPgCf0ttcifQkGdXoh7K-DHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});